const examLessons: Lesson[] = [
  {
    id: 'exam-1',
    chapterId: 'chapter-5',
    titleDe: 'Umweltbewusstes Fahren',
    titleEn: 'Eco-Friendly Driving',
    descriptionDe: 'Spritsparendes Fahren und niedrige Drehzahlen',
    descriptionEn: 'Fuel-efficient driving and low RPMs',
    completed: false,
    isPremium: true,
    tips: [
      {
        id: 'eco-tip1',
        titleDe: 'Früh hochschalten',
        titleEn: 'Shift up early',
        contentDe: 'Zwischen 2000-2500 U/min hochschalten. Niedertouriges Fahren spart Kraftstoff und wird in der Prüfung positiv bewertet.',
        contentEn: 'Shift up between 2000-2500 RPM. Low-rev driving saves fuel and is positively assessed in the exam.',
        type: 'info',
      },
      {
        id: 'eco-tip2',
        titleDe: 'Vorausschauend fahren',
        titleEn: 'Drive anticipatively',
        contentDe: 'Rollen lassen statt bremsen, wenn eine Ampel rot ist. Den Verkehr weit vorn beobachten.',
        contentEn: 'Coast instead of braking when a light is red. Watch traffic far ahead.',
        type: 'info',
      },
    ],
  },
  {
    id: 'exam-1a',
    chapterId: 'chapter-5',
    titleDe: 'Fahrzeug sicher verlassen (Holländischer Griff)',
    titleEn: 'Exiting the Vehicle Safely (Dutch Reach)',
    descriptionDe: 'Sicheres Türöffnen am Ende der Prüfung und im Alltag – besonders wegen Radfahrern und E-Scootern.',
    descriptionEn: 'Safe door opening at the end of the exam and in everyday driving – especially because of cyclists and e-scooters.',
    completed: false,
    isPremium: true,
    glossary: [
      {
        id: 'exit-g1',
        german: 'Holländischer Griff',
        english: 'Dutch Reach',
        noteDe: 'Die Tür mit der weiter entfernten Hand öffnen, damit sich der Oberkörper automatisch dreht und der Schulterblick leichter fällt.',
        noteEn: 'Open the door with the far hand so the upper body turns automatically and the shoulder check becomes more natural.',
      },
    ],
    guidedPoints: [
      {
        id: 'exit-gp1',
        titleDe: 'Vor dem Öffnen Spiegel prüfen',
        titleEn: 'Check mirrors before opening',
        contentDe: 'Blick in den Innenspiegel und linken Außenspiegel.',
        contentEn: 'Look in the interior mirror and left side mirror.',
      },
      {
        id: 'exit-gp2',
        titleDe: 'Schulterblick nach hinten',
        titleEn: 'Shoulder check to the rear',
        contentDe: 'Prüfen, ob ein Radfahrer oder Pkw von hinten kommt.',
        contentEn: 'Check if a cyclist or car is coming from behind.',
        emphasis: 'safety',
      },
      {
        id: 'exit-gp3',
        titleDe: 'Tür nur einen Spalt öffnen',
        titleEn: 'Open door only a crack',
        contentDe: 'Zuerst nur kurz öffnen, um erneut zu sichern, bevor man ganz aussteigt.',
        contentEn: 'Open only a little bit first to check again before getting out completely.',
      },
    ],
  },
  {
    id: 'exam-2',
    chapterId: 'chapter-5',
    titleDe: 'Prüfungsangst bewältigen',
    titleEn: 'Handling Exam Anxiety',
    descriptionDe: 'Tipps gegen Nervosität am Prüfungstag',
    descriptionEn: 'Tips against nervousness on exam day',
    completed: false,
    isPremium: true,
    tips: [
      {
        id: 'anxiety-tip1',
        titleDe: 'Der Prüfer will dass Sie bestehen!',
        titleEn: 'The examiner wants you to pass!',
        contentDe: 'Der Prüfer bewertet nach dem Fahraufgabenkatalog - objektiv und fair. Kleine Fehler führen nicht zum Durchfallen.',
        contentEn: 'The examiner evaluates according to the driving task catalog - objectively and fairly. Small mistakes don\'t mean failure.',
        type: 'success',
      },
      {
        id: 'anxiety-tip2',
        titleDe: 'Ausreichend Schlaf',
        titleEn: 'Get enough sleep',
        contentDe: 'Gehen Sie früh ins Bett und verzichten Sie auf zu viel Koffein vor der Prüfung.',
        contentEn: 'Go to bed early and avoid too much caffeine before the exam.',
        type: 'info',
      },
    ],
  },
  {
    id: 'exam-2a',
    chapterId: 'chapter-5',
    titleDe: 'Top-Gründe für das Nichtbestehen',
    titleEn: 'Top Reasons for Failing',
    descriptionDe: 'Die wichtigsten Situationen, die in der praktischen Prüfung direkt zum Nichtbestehen führen können.',
    descriptionEn: 'The most important situations that can lead to an immediate fail in the practical exam.',
    completed: false,
    isPremium: true,
    guidedPoints: [
      {
        id: 'fail-gp1',
        titleDe: 'Gefährdung geht immer vor Formfehler',
        titleEn: 'Danger to others matters more than style mistakes',
        contentDe: 'Wer Vorfahrt nimmt, Fußgänger gefährdet, rote Ampeln missachtet oder massiv unsicher fährt, fällt in der Regel sofort durch.',
        contentEn: 'Taking priority, endangering pedestrians, running a red light, or driving with serious insecurity usually leads to immediate failure.',
        emphasis: 'safety',
      },
      {
        id: 'fail-gp2',
        titleDe: 'Schulterblick kann entscheidend sein',
        titleEn: 'A missing shoulder check can be decisive',
        contentDe: 'Einmal vergessen ist oft kein Problem, aber mehrmaliges Ignorieren des Schulterblicks (z.B. beim Abbiegen) führt zum Nichtbestehen.',
        contentEn: 'Forgetting once is often no problem, but repeatedly ignoring the shoulder check (e.g. when turning) leads to failure.',
      },
    ],
  },
  {
    id: 'exam-3',
    chapterId: 'chapter-5',
    titleDe: 'Prüfungsreife & Checkliste',
    titleEn: 'Exam Readiness & Checklist',
    descriptionDe: 'Letzte Kontrolle vor der praktischen Prüfung.',
    descriptionEn: 'Final check before the practical driving exam.',
    completed: false,
    isPremium: true,
    scenarios: [
      {
        id: 'exam-first-minutes',
        title: 'Die ersten Minuten',
        situation: 'Der Prüfer stellt sich vor, kontrolliert den Ausweis und stellt ggf. technische Fragen zum Fahrzeug.',
        steps: [
          {
            id: 1,
            title: 'Dokumente bereithalten',
            description: 'Lichtbildausweis oder Reisepass griffbereit haben.',
            icon: 'FileText',
          },
          {
            id: 2,
            title: 'Sitz & Spiegel einstellen',
            description: 'Auch wenn es schon passt: Kurz prüfen und ggf. nachstellen, um Sorgfalt zu zeigen.',
            icon: 'Settings',
          },
          {
            id: 3,
            title: 'Gurt anlegen',
            description: 'Nicht vergessen, bevor der Motor gestartet wird!',
            icon: 'CheckCircle',
          },
        ],
      },
    ],
    tips: [
      {
        id: 'check-tip1',
        titleDe: 'Mitbringen zur Prüfung',
        titleEn: 'Bring to the exam',
        contentDe: '✓ Personalausweis/Reisepass ✓ Ggf. Sehhilfe (Brille) ✓ Bescheinigung Theorieprüfung ✓ Ausbildungsnachweis',
        contentEn: '✓ ID/Passport ✓ Glasses if needed ✓ Theory test certificate ✓ Training documentation',
        type: 'warning',
      },
      {
        id: 'check-tip2',
        titleDe: 'Prüfungsdauer',
        titleEn: 'Exam duration',
        contentDe: 'Die praktische Prüfung dauert ca. 45 Minuten. 3 Grundfahraufgaben werden geprüft (aus dem Katalog ausgewählt).',
        contentEn: 'The practical exam lasts approx. 45 minutes. 3 basic maneuvers are tested (selected from catalog).',
        type: 'info',
      },
    ],
  },
  {
    id: 'exam-sim',
    chapterId: 'chapter-5',
    titleDe: 'Test-Prüfung: Live-Sim',
    titleEn: 'Mock Exam: Live Sim',
    descriptionDe: 'Realistische Simulation mit Zeitdruck und Feedback.',
    descriptionEn: 'Realistic simulation with time pressure and feedback.',
    completed: false,
    isPremium: true,
    isInteractive: true,
  },
];
