// AUTO-GENERATED by scripts/gen-narrator-timings.mjs (en). Do not edit.
export const NARR_FPS = 30;
export const NARR_SEG_FRAMES = [115,118,190,207,179,99,123] as const;
export const NARR_SEG_STARTS = [0,115,233,423,630,809,908] as const;
export const NARR_SPEECH_FRAMES = 1031;
export const NARR_END_CARD_FRAMES = 80;
export const NARR_TOTAL_FRAMES = 1031 + 80;
